desktop-kit/curated/x11-libs/fox/autogen.yaml
desktop-kit/curated/x11-libs/fox/generator.py
desktop-kit/curated/x11-libs/fox/templates/fox.tmpl

This reverts commit 204549c7cef2617317a3240a12c21db9d9de899a.

Revert "Removed from tree as it's prevent a initial tree regenration"

---

games-kit/curated/templates/odamex.tmpl

This change probably won't fix the autogen issue (seems to be a metatools bug) but will clean up the generated ebuilds.

[games-kit] Odamex: improve template

---

core-kit/next/sys-libs/readline/autogen.py

The patches only need to be applied to versions like `8.2`, and now (but perhaps not previously) there is a tarball for `8.2.13`, the current version after patching.  The `autogen.py` seemingly did not expect this case.

Correct verson handling for patchlevel

---

core-kit/next/app-admin/anise-build/autogen.yaml
core-kit/next/app-admin/anise-build/templates/anise-build.tmpl
core-kit/next/app-admin/anise-portage-converter/autogen.yaml
core-kit/next/app-admin/anise-portage-converter/templates/anise-portage-converter.tmpl
core-kit/next/app-admin/anise/autogen.yaml
core-kit/next/app-admin/anise/files/anise.yaml
core-kit/next/app-admin/anise/files/geaaru-repo-index.yml
core-kit/next/app-admin/anise/templates/anise.tmpl

Adding `anise`, `anise-build` and `anise-portage-converter` under `app-admin` category.
Bugs: #macaroni-os/mark-issues#5

Add macaroni tools (WIP)

---

core-kit/curated/sys-kernel/genkernel/genkernel-4.3.10.ebuild

Fixes bug with gz -> bz2 archive for dmraid.

[kernel] Genkernel: Be sure to reformat archive _before_ installing

---

core-kit/curated/sys-kernel/genkernel/autogen.yaml

... so that the bugfix propagates properly.

[kernel] Bump genkernel revision to -r1

---

python-modules-kit/next/dev-python/autogen.yaml

Reverts macaroni-os/kit-fixups#32

Revert "The setuptools scm autogen for version 8"

---

core-kit/next/app-admin/entities/autogen.yaml
core-kit/next/app-admin/entities/templates/entities.tmpl

Add app-admin/entities package

---

core-kit/curated/net-misc/openssh/autogen.yaml
core-kit/curated/net-misc/openssh/templates/openssh.tmpl

Closes: macaroni-os/mark-issues#36

[core-kit] net-misc/openssh: Pin v9.8_p1

---

core-kit/next/sys-devel/gcc/gcc-11.3.0-r1.ebuild
core-kit/next/sys-devel/gcc/gcc-12.2.0.ebuild
core-kit/next/sys-devel/gcc/gcc-12.3.0.ebuild

Closes: macaroni-os/mark-issues#34

sys-devel/gcc: Rebranding

---

python-modules-kit/curated/dev-python/autogen.yaml

Closes https://github.com/macaroni-os/mark-issues/issues/69

=dev-python/m2crypto-0.42 pypi name

---

browser-kit/curated/www-client/firefox/autogen.yaml

=www-client/firefox-129.0

---

generators/pypi-compat-1.py

Closes: macaroni-os/mark-issues#79

generators/pypi-compat-1: Permit to set template

---

core-kit/curated/sys-apps/file/templates/file.tmpl
net-kit/mark/net-misc/s3cmd/autogen.yaml
net-kit/mark/packages.yaml
net-kit/packages.yaml
python-modules-kit/mark/dev-python/autogen.yaml

Closes: macaroni-os/mark-issues#90

[net-kit] autogen net-misc/s3cmd

---

net-kit/mark/net-misc/usbip/autogen.py
net-kit/mark/net-misc/usbip/files/usbipd.confd
net-kit/mark/net-misc/usbip/files/usbipd.initd
net-kit/mark/net-misc/usbip/templates/usbip.tmpl
net-kit/mark/packages.yaml
net-kit/packages.yaml

Closes: macaroni-os/mark-issues#91

[net-kit] net-misc/usbip autogen

---

net-kit/curated/net-misc/dropbox/autogen.py
net-kit/curated/net-misc/dropbox/templates/dropbox.tmpl

Closes: macaroni-os/mark-issues#95

[net-misc] net-misc/dropbox - drop x86 support

---

core-server-kit/curated/autogen.yaml

Closes: macaroni-os/mark-issues#72

[core-server-kit] dev-php/pecl-mongodb pin v1.16.2

---

python-modules-kit/curated/dev-python/autogen.yaml

Closes: macaroni-os/mark-issues#96

[python-modules-kit] dev-python/automat - Review autogen

---

media-kit/curated/media-libs/openimageio/templates/openimageio.tmpl

Closes: macaroni-os/mark-issues#112

[media-kit] media-libs/openimageio - Update template

---

dev-kit/mark/dev-util/mark-devkit/autogen.yaml
dev-kit/mark/dev-util/mark-devkit/templates/mark-devkit.tmpl

Closes: macaroni-os/mark-issues#115

[dev-kit] Add dev-util/mark-devkit package

---

python-modules-kit/curated/dev-python/autogen.yaml

Closes: macaroni-os/mark-issues#87
```
$ doit --pkg pyjwt --release mark                                                                                                                                                      
INFO     Autogen: dev-python/pyjwt (latest)                                                                                                                                                                                                                                                                                                              
INFO     Created: ../dev-python/pyjwt/pyjwt-2.9.0.ebuild   
```

[python-modules-kit] dev-python/pyjwt - Update pypi name

---

python-modules-kit/curated/dev-python/autogen.yaml
python-modules-kit/curated/www-servers/autogen.yaml
python-modules-kit/mark/dev-python/autogen.yaml
python-modules-kit/mark/virtual/autogen.yaml

Closes: macaroni-os/mark-issues#71
:boom: a big change... to test with attention in `mark-testing` branch.

Cleanup python 2.7 compat ebuilds

---

core-kit/curated/net-misc/curl/templates/curl.tmpl

The CHANGES file is now CHANGES.md
Closes: macaroni-os/mark-issues#121

[core-kit] net-misc/curl align autogen

---

security-kit/curated/sys-process/audit/autogen.yaml

Closes: macaroni-os/mark-issues#73
```
$ doit --release mark
INFO     Autogen: sys-process/audit-4.0.1                                                                                                                                        
INFO     Created: audit-4.0.1.ebuild                                                                                                                                             
```

[security-kit] sys-process/audit - Pin v4.0.1

---

science-kit/curated/sci-mathematics/rstudio-bin/autogen.py
science-kit/curated/sci-mathematics/rstudio-bin/templates/rstudio-bin.tmpl

getting QA about missing libssl.so.3, libcrypto.so.3 
probably needs https://github.com/macaroni-os/mark-issues/issues/47 
see https://github.com/macaroni-os/mark-issues/issues/126

sci-mathematics/rstudio-bin refactoring

---

generators/gitlab-1.py

Closes: macaroni-os/mark-issues#139

[core-kit] Restore `gitlab-1` generators

---

desktop-kit/mark/x11-themes/gnome-orchis-theme/autogen.yaml
desktop-kit/mark/x11-themes/gnome-orchis-theme/templates/gnome-orchis-theme.tmpl

Closes: macaroni-os/macaroni-issues#144
Bugs: macaroni-os/macaroni-funtoo#47

[desktop-kit] Add x11-themes/gnome-orchis-theme

---

desktop-kit/mark/x11-themes/papirus-icon-theme/autogen.yaml
desktop-kit/mark/x11-themes/papirus-icon-theme/templates/papirus-icon-theme.tmpl

Closes: macaroni-os/mark-issues#145

[desktop-kit] x11-themes/papirus-icon-theme autogen

---

releases/mark/repositories.yaml

Closes: macaroni-os/mark-issues#146

[xfce-kit] Now managed by kit-fixups

---

core-server-kit/curated/dev-db/arangodb/autogen.py
core-server-kit/curated/dev-db/postgresql/generator.py
desktop-kit/curated/x11-terms/kitty/templates/kitty-shell-integration.tmpl
desktop-kit/curated/x11-terms/kitty/templates/kitty-terminfo.tmpl
desktop-kit/curated/x11-terms/kitty/templates/kitty.tmpl
media-kit/curated/media-gfx/darktable/autogen.yaml
python-modules-kit/curated/dev-python/autogen.yaml

Closes: macaroni-os/mark-issues#150

Cleanup `next` KEYWORDS on mark release

---

net-kit/mark/net-misc/lksctp-tools/autogen.yaml
net-kit/mark/net-misc/lksctp-tools/templates/lksctp-tools.tmpl
net-kit/mark/packages.yaml
net-kit/packages.yaml

Closes: macaroni-os/mark-issues#147

[net-kit] net-misc/lksctp-tools autogen

---

net-kit/mark/net-im/mattermost-desktop-bin/autogen.yaml
net-kit/mark/net-im/mattermost-desktop-bin/templates/mattermost-desktop-bin.tmpl
net-kit/mark/packages.yaml
net-kit/packages.yaml

Closes: macaroni-os/mark-issues#114

[net-kit] net-im/mattermost-desktop-bin autogen

---

core-hw-kit/mark/sys-firmware/ipxe/autogen.yaml
core-hw-kit/mark/sys-firmware/ipxe/metadata.xml
core-hw-kit/mark/sys-firmware/ipxe/templates/ipxe.tmpl
core-kit/curated/app-emulation/qemu/qemu-7.1.0.ebuild

Bugs: macaroni-os/mark-issues#160

[core-hw-kit] sys-firmware/ipxe autogen

---

core-kit/curated/eclass/distutils-r1.eclass

Closes: macaroni-os/mark-issues#159

[core-kit][eclass] distutils-r1: Fix meson-python

---

net-kit/curated/mail-mta/ssmtp/files/patches/0010_all_maxsysuid.patch
net-kit/curated/mail-mta/ssmtp/files/patches/0020_all_from-format-fix.patch
net-kit/curated/mail-mta/ssmtp/files/patches/0030_all_authpass.patch
net-kit/curated/mail-mta/ssmtp/files/patches/0040_all_darwin7.patch
net-kit/curated/mail-mta/ssmtp/files/patches/0050_all_strndup.patch
net-kit/curated/mail-mta/ssmtp/files/patches/0060_all_opessl_crypto.patch
net-kit/curated/mail-mta/ssmtp/files/patches/0070_all_solaris-basename.patch
net-kit/curated/mail-mta/ssmtp/files/patches/0080_all_gnutls.patch
net-kit/curated/mail-mta/ssmtp/files/patches/0090_all_debian-remote-addr.patch
net-kit/curated/mail-mta/ssmtp/files/patches/0100_all_ldflags.patch
net-kit/curated/mail-mta/ssmtp/files/patches/0110_all_stdint.patch
net-kit/curated/mail-mta/ssmtp/files/patches/0120_all_aliases.patch
net-kit/curated/mail-mta/ssmtp/files/patches/0130_all_garbage-writes.patch
net-kit/curated/mail-mta/ssmtp/templates/ssmtp.tmpl

Closes: macaroni-os/mark-issue#58
Run `doit`:
```
$ doit --release mark
INFO     Autogen: mail-mta/ssmtp (latest)                                                                                                                                                                           
INFO     Created: ssmtp-2.64-r4.ebuild                                     
```
Testing emerge:
```
>>> Installing (1 of 1) mail-mta/ssmtp-2.64-r4::net-kit
```

[net-kit] mail-mtp/ssmtp review

---

core-kit/curated/sys-fs/multipath-tools/metadata.xml
core-kit/curated/sys-fs/multipath-tools/templates/multipath-tools.tmpl
core-kit/mark/packages.yaml.wip

Apply patch from macaroni sambuca stack.
Closes: macaroni-os/mark-issues#17

[core-kit] sys-fs/multipath-tools review

---

ruby-kit/next/dev-ruby/autogen.yaml

Summary
========
* Closes: macaroni-os/mark-issues#174

=dev-ruby/json-2.7.4 user change on github flory -> ruby

---

media-kit/mark/media-gfx/qrencode/autogen.yaml
media-kit/mark/media-gfx/qrencode/templates/qrencode.tmpl
media-kit/mark/packages.yaml
media-kit/packages.yaml

Closes: macaroni-os/mark-issues#173

[media-kit] media-gfx/qrencode autogen

---

desktop-kit/curated/app-backup/borgbackup/autogen.yaml

* replace llfuse with pyfuse3
* add dependency to xxhash
Closes: macaroni-os/mark-issues#101

[desktop-kit] app-backup/borgbackup review

---

browser-kit/curated/www-client/firefox/autogen.yaml
browser-kit/curated/www-client/firefox/templates/firefox.tmpl

```
emerge -av www-client/firefox
These are the packages that would be merged, in order:
Calculating dependencies... done!
[ebuild     U  ] www-client/firefox-132.0:0/132::public-overlay [131.0:0/131::public-overlay] USE="X clang dbus gmp-autoupdate openh264 pulseaudio system-jpeg system-libevent -debug -eme-free -geckodriver -hardened -hwaccel -jack -libproxy -lto -pgo -screencast (-selinux) -sndio -system-av1 -system-harfbuzz (-system-icu) -system-libvpx -system-png -system-python-libs -system-webp -wayland -wifi" L10N="de -ach -af -an -ar -ast -az -be -bg -bn -br -bs -ca -ca-valencia -cak -cs -cy -da -dsb -el -en-CA -en-GB -en-US -eo -es-AR -es-CL -es-ES -es-MX -et -eu -fa -ff -fi -fr -fur -fy-NL -ga-IE -gd -gl -gn -gu-IN -he -hi-IN -hr -hsb -hu -hy-AM -ia -id -is -it -ja -ka -kab -kk …
```

=www-client/firefox-132.0

---

python-modules-kit/curated/dev-python/templates/numpy.tmpl

Closes: macaroni-os/mark-issues#189

[python-modules-kit] dev-python/numpy add +lapack

---

net-kit/mark/net-misc/lksctp-tools/templates/lksctp-tools.tmpl

Closes: macaroni-os/mark-issues#147

[net-kit] net-misc/lksctp-tools fix post_src_unpack

---

core-kit/curated/eclass/distutils-r1.eclass
python-modules-kit/curated/dev-python/autogen.yaml
python-modules-kit/mark/dev-python/autogen.yaml

Closes: macaroni-os/mark-issues#205

[python-modules-kit] dev-python/license-expression autogen review

---

core-kit/curated/app-misc/skim/autogen.yaml
core-kit/curated/app-misc/skim/templates/skim.tmpl

```
╰ $ doit
INFO     Autogen: app-misc/skim (latest)                                                                                                                                                                                                                                                                            
INFO     Download from https://github.com/skim-rs/skim/tarball/32d9e70af4eeaaf2c3f2d276838dc338361a75cf verified as valid tar.gz archive.                                                                                                                                                                           
INFO     Created: skim-0.11.11.ebuild       
```

app-misc/skim github user changed

---

games-kit/curated/autogen.yaml

Summary
========
* Change the source URI for Eviternity II from "Eviternity-II.zip" to "Eviternity-II-Final.zip" in autogen.yaml. This ensures the correct final version file is referenced.
Test Plan
========
* Doit
```
doit --pkg eviternity-ii
INFO     Autogen: games-fps/eviternity-ii-1.0_rc5                                                                                                                                                                          
INFO     Created: games-fps/eviternity-ii/eviternity-ii-1.0_rc5.ebuild                                                                                                                                                     
99% Eviternity-II-Final.zip ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ …
```

games-fps/everternity-ii updated Eviternity II src_uri

---

core-hw-kit/curated/sys-apps/fwupd/templates/fwupd.tmpl

Review meson configure phase is order to use
correctly meson_feature instead of meson_use.
Closes: macaroni-os/mark-issues#223

[core-hw-kit] sys-apps/fwupd review template

---

core-gl-kit/next/dev-util/intel_clc/intel_clc-24.2.4.ebuild
media-kit/curated/media-gfx/inkscape/templates/inkscape.tmpl

This fix Inkscape and intel_clc.
Closes: macaroni-os/mark-issues#228

Move KEYWORDS="next" to KEYWORDS="*"
