core-kit/curated/sys-kernel/genkernel/autogen.yaml, core-kit/curated/sys-kernel/genkernel/files/genkernel-4.bash, core-kit/curated/sys-kernel/genkernel/templates/genkernel.tmpl
Genkernel has features still unsupported by `ramdisk`, and the latter can probably be expected to be unmaintained unless we adopt it.  I'd like to add Genkernel to our tree, for now, until we decide what to do.
=> Add autogen for Genkernel, without touching existing static ebuild.

llvm-kit/curated/sys-devel/clang/clang-16.0.0.ebuild
Implements the ebuild correction from a (now unavailable) Funtoo Jira issue.
=> Fix for clang-16, from FL-12402

core-kit/curated/sys-kernel/genkernel/templates/genkernel.tmpl
Genkernel does not install on machines that don't have `a2x` (from `asciidoc`) present.
=> [core-kit] add app-text/asciidoc to build-time deps for genkernel

python-modules-kit/next/dev-python/autogen.yaml
It one of dependencies to have fixed PyQt5 on MARK, issuse macaroni-os/mark-issues#14 
I performed kit-fixups PR while ago, sorry for mistakes beforehand
I used older stage3 (2024-07-15 from funtoo), because last one was on x86-64-x4 architecture
There are error message "ERROR setuptools_scm._file_finders.git listing git files failed - pretending there aren't any", but assume it safe to ignore https://github.com/pypa/setuptools_scm/issues/997#issuecomment-2032361400
doit:
```shell
$ doit --pkg setuptools_scm
INFO     Autogen: dev-python/setuptools_scm (latest)                                                                                                                                          
WARNING  dict key du_pep517 overwritten. …
```
=> The setuptools scm autogen for version 8

core-kit/curated/sys-kernel/genkernel/templates/genkernel.tmpl
Mistakenly committed static ebuild with the change; removed the ebuild,
so now the fix needs to be re-applied, in the right place.
=> [HOTFIX] [kernel] Genkernel: Ensure that gz -> gz2 is solved in template, not ebuild

core-kit/next/sys-kernel/debian-sources/debian-sources-6.9.10_p1.ebuild
At the time when the host is accesssible, before sandboxing, the ${D} dir tree does not exist yet; so $WORKDIR can be used.  It was partially done in a previous commit, but not changed in the actual call to `genkernel`.  This PR fixes that Bug.
=> [HOTFIX] [kernel] Genkernel: Use a subdir of $WORKDIR for genkernel cache.

net-kit/curated/net-dns/coredns/templates/coredns.tmpl
Closes: macaroni-os/mark-issues#52
=> [net-kit] net-dns/coredns: Fix emerge with go1.22

core-kit/curated/eclass/toolchain-gcc.eclass
Closes: macaroni-os/mark-issues#34
=> [core-kit] [toolchain-gcc.eclass] GCC rebranding

python-modules-kit/mark/dev-python/autogen.yaml
Did more extensive tests and doesn't look like there are problem, although to be sure the rebuilding stage3 is not bad idea.
my extensive tests where:
```bash
$ cd /var/db/pkg
$ find -name "*.ebuild"|xargs grep -m1 --color=always setuptools_scm
```
and remerge these packages with updated version (interestingly is not much of them).
More about PR
============
it is one step to fix https://github.com/macaroni-os/mark-issues/issues/14 , the updated setuptools_scm necessary for dev-python/sip package upgrade which resolves problem.
The bug (duplicated entrypoints) in setuptools_scm using python 3.9 is very similar to https://github.com/pypa/setuptools/issues/3649 , only difference the bug is during install.
On other hand using python 3.12 (on Gentoo) entry points are correct.
doit
==== …
=> Take 3 on setuptools_scm package

python-modules-kit/curated/dev-python/autogen.yaml
Closes: macaroni-os/mark-issues#82
=> [python-modules-kit] dev-python/cython needs pypi name fix

net-kit/next/net-misc/networkmanager/autogen.yaml, net-kit/next/net-misc/networkmanager/generator.py
Pins NM to version `1.48.6`, the last version that builds successfully in our tree until we update our kernel headers to `>=linux-headers-6.8`.
=> [bugfix] [feature] Add version-pinning to networkmanager generator & YAML

python-modules-kit/curated/dev-python/autogen.yaml
I modified curated directly, alhough setuptools_scm are in mark directory (maybe correct this time)
as usual
```bash
$ doit --release mark --pkg sip
WARNING  dict key du_pep517 overwritten.
WARNING  dict key du_pep517 overwritten.
INFO     Autogen: dev-python/sip (latest)
WARNING  dict key du_pep517 overwritten.
INFO     Created: sip/sip-6.8.6.ebuild
```
using stage3-generic_64-v3-next-2024-07-15.tar.xz from funtoo as base
```bash
fchroot # USE="pcre16" emerge -avq setuptools_scm sip PyQt5
* IMPORTANT: config file '/etc/portage/package.use' needs updating.
* See the CONFIGURATION FILES and CONFIGURATION FILES UPDATE TOOLS
* sections of the emerge man page to learn how to update config files.
[ebuild   R   ] dev-libs/libpcre2-10.35  USE="bzip2 jit pcre16* pcre32 readline recursion-limit …
```
=> Updated sip autogen

dev-kit/curated/dev-libs/libfilezilla/autogen.py, net-kit/curated/net-ftp/filezilla/autogen.py
Summary
========
* Seems like the page is expecting a 'User-Agent' header in the request from now
* This closing https://github.com/macaroni-os/mark-issues/issues/108
Test Plan
========
* Doit
```
╰ $ doit
INFO     Autogen: net-ftp/filezilla (latest)                                                                                                                                                                                                                                                                        
INFO     Download from https://dl1.cdn.filezilla-project.org/client/FileZilla_3.67.1_src.tar.xz?h=smZwSoLKpKnNpdLs2Hag5A&x=1725052174 verified as valid tar.xz archive. …
```
=> =net-ftp/filezilla-3.67.1 and dev-libs/libfilezilla-0.48.1 prevent tree  regeneration

python-modules-kit/curated/dev-python/autogen.yaml
Closes: macaroni-os/mark-issues#107
=> [python-modules-kit] dev-python/pyyaml - Drop cython3 mark

media-kit/mark/media-sound/mpd/files/040-lib-fmt-support-build-with-libfmt-11.0.0.patch, media-kit/mark/media-sound/mpd/files/mpd-fmt11_e380ae9.patch, media-kit/mark/media-sound/mpd/templates/mpd.tmpl
Closes: macaroni-os/mark-issues#113
Tested on macaroni-funtoo tree. The package is available in Phoenix 24.08.
=> [media-kit] media-sound/mpd - fix compilation with fmt 11

core-kit/curated/app-emulation/virtualbox-bin/autogen.py
The url for extension pack has been changed from
`https://download.virtualbox.org/virtualbox/7.1.0/Oracle_VM_VirtualBox_Extension_Pack-7.1.0.vbox-extpack`
to 
`https://download.virtualbox.org/virtualbox/7.1.0/Oracle_VirtualBox_Extension_Pack-7.1.0.vbox-extpack`
See https://download.virtualbox.org/virtualbox/7.1.0/
=> =app-emulation/virtualbox-bin-7.1.0 breaks tree autogen

python-modules-kit/curated/dev-python/autogen.yaml
Closes: macaroni-os/mark-issues#122
=> [python-modules-kit] dev-python/sqlalchemy fix pypi name

core-kit/curated/sys-apps/busybox/autogen.yaml, core-kit/curated/sys-apps/busybox/files/busybox-1.36.1-no-cbq.patch, core-kit/curated/sys-apps/busybox/templates/busybox.tmpl
Using `dirlisting-1` generator and add patch
for CBQ feature removed.
Closes: macaroni-os/mark-issues#123
=> [core-kit] sys-apps/busybox autogen review

science-kit/curated/sci-mathematics/rstudio-bin/autogen.py
Closes: macaroni-os/mark-issues#126
```
╰ $ doit
INFO     Autogen: sci-mathematics/rstudio-bin (latest)                                                                                                                                                                                                                                                              
INFO     Download from https://download1.rstudio.org/electron/focal/amd64/rstudio-2024.04.2-764-amd64-debian.tar.gz verified as valid tar.gz archive.                                                                                                                                                               
INFO     Created: rstudio-bin-2024.04.2.764.ebuild   ```
=> sci-mathematics/rstudio-bin

core-kit/next/app-eselect/eselect-java/Manifest, core-kit/next/app-eselect/eselect-java/eselect-java-0.5.1.ebuild, core-kit/next/packages.yaml, core-kit/next/packages.yaml.wip, core-kit/packages.yaml
Summary
========
* static ebuild added
* deleted from gentoo stage
* Closes: macaroni-os/mark-issues#130
Test Plan
========
* Doit
```
╰ $ ebuild eselect-java-0.5.1.ebuild digest
Appending /home/borisp/Development/src/funtoo-infra-core/kit-fixups/core-kit/next to PORTDIR_OVERLAY...
>>> Downloading 'https://gitweb.gentoo.org/proj/eselect-java.git/snapshot/eselect-java-0.5.1.tar.gz'
--2024-09-19 21:58:42--  https://gitweb.gentoo.org/proj/eselect-java.git/snapshot/eselect-java-0.5.1.tar.gz
Resolving gitweb.gentoo.org... 146.75.121.91, 2a04:4e42:8d::347
Connecting to gitweb.gentoo.org|146.75.121.91|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15205 (15K) [application/x-gzip]
Saving to: ‘/var/cache/portage/distfiles/eselect-java-0.5.1.tar.gz.__download__’ …
```
=> app-eselect/eselect-java

core-hw-kit/curated/sys-apps/fwupd/autogen.yaml, core-hw-kit/curated/sys-apps/fwupd/templates/fwupd.tmpl
Summary
========
* fixed autogen
* fixed template
* Closes: macaroni-os/mark-issues#132
Test Plan
========
* Doit
```
INFO     Autogen: dev-python/pefile (latest)
INFO     Autogen: sys-apps/fwupd (latest)
INFO     Autogen: sys-apps/fwupd-efi (latest)
INFO     Created: ../../dev-python/pefile/pefile-2024.8.26.ebuild
INFO     Created: fwupd-1.9.24.ebuild
INFO     Download from https://github.com/fwupd/fwupd-efi/tarball/03545b505ac821c967e0868be22aa9a55e77981d verified as valid tar.gz archive.
INFO     Created: ../fwupd-efi/fwupd-efi-1.7.ebuild
```
* Make it available in a own repo tree or by seeding into a local overlay
* Emerge it
```
Updating profiles at /etc/portage/make.profile/parent...
Sync successful and kits in alignment! :)
workstation-funmore-repo ~ # emerge -av sys-apps/fwupd …
```
=> sys-apps/fwupd

lang-kit/curated/dev-lang/R/templates/R.tmpl
Summary
========
* Enabled lapack use flag by default
* Closes: macaroni-os/mark-issues#133
=> dev-lang/R enable lapack by default

net-kit/curated/net-vpn/openconnect/openconnect-8.10.ebuild
The existing linux-info eclass is used only to
check if the `tun` kernel driver is present.
We consider the `tun` kernel driver present by default and in our kernel configs.
We could eventually to add an `einfo` message about the needs of CONFIG_TUN in the future.
Closes: macaroni-os/mark-issues#60
=> [net-kit] net-vpn/openconnect - Drop dependency from kernel

lang-kit/curated/dev-lang/autogen.yaml
Summary
========
* Closes: https://github.com/macaroni-os/mark-issues/issues/131
* This updates MARK to the latest upstream Go stable versions: Go 1.23.1 and 1.22.7
Test Plan
=======
I unfortunately cannot test this properly as I cannot get the forked funtoo-metatools to even work with the new MARK kit-fixups:
```
doit --cat dev-lang --pkg go
Traceback (most recent call last):
File "/home/ss/Repos/funtoo-metatools-macaroni/bin/doit", line 102, in <module>
success = asyncio.run(main_thread())
File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
return future.result()
File "/home/ss/Repos/funtoo-metatools-macaroni/bin/doit", line 91, in main_thread
await …
```
=> adding go1.22.7 and go1.23.1

net-kit/curated/mail-client/thunderbird-bin/autogen.py, net-kit/curated/mail-client/thunderbird-bin/templates/thunderbird-bin.tmpl
Summary
========
* removed esr from ebuild name, as portage reports invalid ebuild name
* Closes: macaroni-os/mark-issues#125
Test Plan
========
* Doit
```
╰ $ doit
INFO     Autogen: mail-client/thunderbird-bin (latest)
INFO     Download from https://archive.mozilla.org/pub/thunderbird/releases/128.2.3esr/linux-i686/en-US/thunderbird-128.2.3esr.tar.bz2 verified as valid tar.bz2 archive.
INFO     Download from https://archive.mozilla.org/pub/thunderbird/releases/128.2.3esr/linux-x86_64/en-US/thunderbird-128.2.3esr.tar.bz2 verified as valid tar.bz2 archive.
INFO     Created: thunderbird-bin-128.2.3.ebuild
```
* Make it available in a own repo tree or by seeding into a local overlay
* Emerge it
```
workstation-mark-repo ~ # emerge -av mail-client/thunderbird-bin
These are the packages that …
```
=> mail-client/thunderbird-bin

python-modules-kit/curated/dev-python/autogen.yaml
Summary
========
* pipy name chnaged
* Closes: macaroni-os/mark-issues#152
Test Plan
========
* Doit
```
╰ $ doit --pkg markupsafe
WARNING  dict key du_pep517 overwritten.                                                                                                                                                                                                                                                                            
WARNING  dict key du_pep517 overwritten.                                                                                                                                                                                                                                                                            
INFO     Autogen: dev-python/markupsafe (latest) …
```
=> =dev-python/markupsafe-3.0.0

core-kit/curated/sys-apps/portage/portage-3.0.14-r13.ebuild
Review GENTOO_MIRRORS to use these hosts:
* https://distfiles.macaronios.org
* https://distfiles-flat.macaronios.org
Closes: macaroni-os/mark-issues#149
=> [core-kit] sys-apps/portage - Bump v3.0.14-r13

python-modules-kit/curated/dev-python/autogen.yaml
Using last available release.
Closes: macaroni-os/mark-issues#85
=> [python-modules-kit] dev-python/zope-interface review

core-kit/curated/sys-boot/syslinux/files/6.04_pre1/0005-stddef_addwchar_t.patch, core-kit/curated/sys-boot/syslinux/syslinux-6.04_pre3.ebuild
* support upx-bin package in alternative of upx
* fix compilation issues after >=gnu-efi-3.0.16
Closes: macaroni-os/mark-issues#161
=> [core-kit] sys-boot/linux review

editors-kit/curated/app-editors/vscode-bin/autogen.py
```
╰ $ doit
INFO     Autogen: app-editors/vscode-bin (latest)                                                                                                                                                                                                                                                                   
INFO     Download from https://update.code.visualstudio.com/1.94.2/linux-x64/stable verified as valid tar.gz archive.                                                                                                                                                                                               
INFO     Created: vscode-bin-1.94.2.ebuild          ```
=>  app-editors/vscode-bin with @geaaru and nemotron:latest ;) 

python-modules-kit/curated/dev-python/autogen.yaml, python-modules-kit/packages.yaml
Closes: macaroni-os/mark-issues#102
Run `doit`:
```
$ doit --release mark --pkg docker-py
INFO     Autogen: dev-python/docker-py (latest)                                                                                                                                                                     
WARNING  dict key du_pep517 overwritten.                                                                                                                                                                            
WARNING  dict key du_pep517 overwritten.                                                                                                                                                                            
WARNING  dict key du_pep517 overwritten. …
```
=> [python-modules-kit] dev-python/docker-py review autogen

core-server-kit/mark/app-backup/backrest/autogen.yaml, core-server-kit/mark/app-backup/backrest/files/backrest.confd, core-server-kit/mark/app-backup/backrest/files/backrest.initd, core-server-kit/mark/app-backup/backrest/files/backrest.service, core-server-kit/mark/app-backup/backrest/templates/backrest.tmpl
Note: ATM to compile the webui you need <nodejs-22. I hope that this will be fixed soon.
Closes: macaroni-os/mark-issues#168
=> [core-server-kit] Add app-backup/backrest autogen

python-modules-kit/curated/dev-python/autogen.yaml
Closes: macaroni-os/mark-issues#170
~ # emerge -av mako
```
These are the packages that would be merged, in order:
Calculating dependencies... done!
[ebuild     U  ] dev-python/mako-1.3.6::python-modules-kit [1.3.5::python-modules-kit] PYTHON_TARGETS="python3_9 -python2_7 -python3_10 -python3_7 -python3_8" 0 KiB
Total: 1 package (1 upgrade), Size of downloads: 0 KiB
Would you like to merge these packages? [Yes/No] 
>>> Verifying ebuild manifests
>>> Emerging (1 of 1) dev-python/mako-1.3.6::python-modules-kit
>>> Installing (1 of 1) dev-python/mako-1.3.6::python-modules-kit
>>> Recording dev-python/mako in "world" favorites file...
>>> Jobs: 1 of 1 complete                           Load avg: 0.92, 0.80, 1.09
* Messages for package dev-python/mako-1.3.6:
* Optional dependencies:
* …
```
=> dev-python/mako pypi name

ruby-kit/next/dev-ruby/templates/json.tmpl
Summary
========
*
* Closes: macaroni-os/mark-issues#174
```
~ # emerge -av dev-ruby/json
These are the packages that would be merged, in order:
Calculating dependencies... done!
[ebuild     U  ] dev-ruby/json-2.7.4:2::ruby-kit [2.7.2:2::ruby-kit] USE="-doc -test" RUBY_TARGETS="ruby31 -ruby27 -ruby30 -ruby32" 0 KiB
Total: 1 package (1 upgrade), Size of downloads: 0 KiB
Would you like to merge these packages? [Yes/No]
>>> Verifying ebuild manifests
>>> Emerging (1 of 1) dev-ruby/json-2.7.4::ruby-kit
>>> Installing (1 of 1) dev-ruby/json-2.7.4::ruby-kit
>>> Recording dev-ruby/json in "world" favorites file...
>>> Jobs: 1 of 1 complete                           Load avg: 3.46, 2.42, 1.25
>>> Auto-cleaning packages...
>>> No outdated packages were found on your system.
* GNU info directory …
```
=> =dev-ruby/json-2.7.4 fix avoiding setting gem

core-hw-kit/curated/sys-power/cpupower/templates/cpupower.tmpl
Fix installation of the libraries in the
right path.
emerge:
```
/usr/sbin/cpufreq-bench
/usr/bin/cpupower
/usr/lib64/libcpupower.so.0.0.1
>>> Installing (1 of 1) sys-power/cpupower-6.11.5::core-hw-kit
>>> Recording sys-power/cpupower in "world" favorites file...
>>> Auto-cleaning packages...
```
Closes: macaroni-os/mark-issues#156
=> [core-hw-kit] sys-power/cpupower - review template

python-modules-kit/mark/dev-python/autogen.yaml, python-modules-kit/packages.yaml
Package no more maintained.
Closes: macaroni-os/mark-issues#175
=> [python-modules-kit] dev-python/llfuse dropped

python-modules-kit/curated/dev-python/autogen.yaml
Closes: macaroni-os/mark-issues#182
doit:
```
$ doit --release mark --pkg motor                                                                                                                                                      
INFO     Autogen: dev-python/motor (latest)                                                                                                                                                                                                                                                                                             
INFO     Created: motor/motor-3.6.0.ebuild                                                                                                                                                       
```
Test:
```
>>> Installing (1 of 1) …
```
=> [python-modules-kit] dev-python/motor fix DEPEND

text-kit/curated/app-text/enchant/autogen.yaml, text-kit/curated/app-text/enchant/templates/enchant.tmpl
Summary
========
* AbiWord is going to personal care of Reuben Thomas so changing the repo. See See https://github.com/rrthomas/enchant/commit/d5346b19b294081d329d70bed0b4eccb09380f4d#diff-7ee66c4f1536ac84dc5bbff1b8312e2eef24b974b3e48a5c5c2bcfdf2eb8f3ceR4
* Closes: macaroni-os/mark-issues#/186
Test Plan
========
* Doit
```
╰ $ doit
INFO     Autogen: app-text/enchant (latest)                                                                                                                                                                                                                                                                         
INFO     Download from https://github.com/rrthomas/enchant/releases/download/v2.8.2/enchant-2.8.2.tar.gz verified as valid tar.gz archive. …
```
=> =app-text/enchant-2.8.2

core-kit/curated/sys-apps/baselayout/baselayout-3.0.ebuild
EROOT is no more initialized with `/` with EAPI 7.
Closes: macaroni-os/mark-issues#187
Test emerge:
```
>>> Installing (1 of 1) sys-apps/baselayout-3.0::core-kit
>>> Auto-cleaning packages...
```
Test `lsb_release`:
```
LSB Version:	n/a
Distributor ID:	macaroni
Description:	Macaroni OS
Release:	n/a
Codename:	mark
```
=> [core-kit] sys-apps/baselayout fix EAPI 7 integration

core-kit/curated/app-emulation/libvirt/templates/libvirt.tmpl
* removing dependency to yajl in favor of json-c
Closes: macaroni-os/mark-issues#185
Emerge test:
```
>>> Installing (1 of 1) app-emulation/libvirt-10.9.0::core-kit
* Important: The openrc libvirtd init script is now broken up into two
* separate services: libvirtd, that solely handles the daemon, and
```
=> [core-kit] app-emulation/libvirt template review

core-kit/curated/sys-kernel/genkernel/autogen.yaml, core-kit/curated/sys-kernel/genkernel/files/share/patches/busybox/1.37.0/busybox-1.36.1-no-cbq.patch, core-kit/curated/sys-kernel/genkernel/templates/genkernel.tmpl
Since `linux-6.8`, changes to the kernel headers necessitate a patch for `busybox-1.36.1` and `busybox-1.37.0`.
This PR does the following:
- Add patch from `sys-apps/busybox` to genkernel's installed files
- (genkernel automatically applies the patch)
- Bump genkernel's internal busybox version to match the current one in MARK tree
Tested with `metro` from a dev tree.  Originally found the issue during `metro` builds on `mark-testing`.  In the `metro` environment, there aren't any cached genkernel `initramfs` segments, so `busybox` needs to be built.  With this patch, `metro` builds succeed on the `mark-testing` tree.
=> [core-kit] [bugfix] Fix genkernel compatibility with updated linux-headers

net-kit/curated/net-p2p/qbittorrent/autogen.yaml
The new versions need openssl 3.x
Closes: macaroni-os/mark-issues#190
=> [net-kit] net-p2p/qbittorrent pinned v4.6.7

net-kit/next/net-analyzer/mtr/autogen.yaml, net-kit/next/net-analyzer/mtr/templates/mtr.tmpl, net-kit/next/packages.yaml, net-kit/packages.yaml
Summary
========
* autogened net-analyzer/mtr 
Test Plan
========
* Doit
```
╰ $ doit
INFO     Autogen: net-analyzer/mtr (latest)                                                                                                                                                                                                                                                                         
INFO     Download from https://github.com/traviscross/mtr/tarball/852e5617fbf331cf292723702161f0ac9afe257c verified as valid tar.gz archive.                                                                                                                                                                        
INFO     Created: mtr-0.95.ebuild   
```
* Make it available in a own repo tree or by seeding …
=> net-analyzer/mtr autogened

python-modules-kit/curated/dev-python/autogen.yaml
Summary
========
* Updated dev-python/packaging to 24.2 needed for =dev-python/hatchling-1.26.0
* Closes: macaroni-os/mark-issues#201
Test Plan
========
* Doit
```
╰ $ doit --pkg packaging
WARNING  dict key du_pep517 overwritten.                                                                                                                                                                                                                                                                            
INFO     Autogen: dev-python/packaging-24.2 …
```
=> =dev-python/packaging-24.2 with new module 'packaging.licenses'

python-modules-kit/curated/dev-python/templates/async_timeout.tmpl
The package `dev-python/async_timeout` doesn't need anymore the MY_PV variable.
Closes: macaroni-os/mark-issues#202
=> [python-modules-kit] dev-python/async_timeout review template

python-modules-kit/mark/dev-python/autogen.yaml, python-modules-kit/packages.yaml
Closes: macaroni-os/mark-issues#207
=> [python-modules-kit] dev-python/pyrfc3339 - fix pypiname

python-modules-kit/mark/dev-python/autogen.yaml
Closes: macaroni-os/mark-issues#215
```
doit --release mark --pkg packaging-legacy
INFO     Autogen: dev-python/packaging-legacy (latest)                                                                                                                                                              
WARNING  dict key du_pep517 overwritten.                                                                                                                                                                            
WARNING  dict key du_pep517 overwritten.                                                                                                                                                                            
WARNING  dict key du_pep517 overwritten. …
```
=> [python-modules-kit] Add dev-python/packaging-legacy

generators/gnu-1.py
Closes: macaroni-os/mark-issues#218
```
INFO     Autogen: sys-apps/util-linux (latest)                                                                                                                                                                      
INFO     Download from https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.40/util-linux-2.40.2.tar.xz verified as valid tar.xz archive.                                                                  
INFO     Created: util-linux-2.40.2.ebuild                                                                                                                                                                          
```
`util-linux` uses `gnu-1` generator.
=> Review `gnu-1` generator to support packaging-24

core-kit/mark/sys-apps/metatools/autogen.yaml, core-kit/mark/sys-apps/metatools/templates/metatools.tmpl
Closes: macaroni-os/mark-issues#217
=> [core-kit] Bump sys-apps/metatools-1.3.8_p20241117

core-kit/mark/sys-apps/metatools/autogen.yaml
Closes: macaroni-os/mark-issues#217
=> [core-kit] sys-apps/metatools: Bump v1.3.8_p20241118

python-modules-kit/mark/dev-python/autogen.yaml, python-modules-kit/packages.yaml
In order to compile this package with packaging 24 we need to use the setuptools backend.
Closes: macaroni-os/mark-issues#220
=> [python-modules-kit] dev-python/python-xlib review backend

desktop-kit/curated/app-office/libreoffice-bin/autogen.py
…etching
Summary
========
* changed the mirror URL to the document foundation archive 
* updated the regular expression for matching version numbers to be more precise. 
Test Plan
========
* Doit
```
doit
INFO     Autogen: app-office/libreoffice-bin (latest)                                                                                                                                                                      
INFO     Download from https://downloadarchive.documentfoundation.org/libreoffice/old//24.8.3.2/rpm/x86_64/LibreOffice_24.8.3.2_Linux_x86-64_rpm.tar.gz verified as valid tar.gz archive.                                  
INFO     Created: libreoffice-bin-24.8.3.2.ebuild …
```
=> app-office/libreoffice-bin ensures the script fetches the correct latest version of LibreOffice binaries

browser-kit/curated/www-client/firefox/autogen.yaml
Summary
========
* Bump Firefox to version 133.0 in autogen.yaml. 
* Adjust associated patchset tarball to reflect the new version.
Test Plan
========
* Doit
```
~/Development/src/funtoo-infra-core/kit-fixups/browser-kit/curated/www-client/firefox git:[funmore]
doit
WARNING  dict key unmasked overwritten.                                                                                                                                                                                    
INFO     Autogen: www-client/firefox-133.0                                                                                                                                                                                 
INFO     Download from https://dev.gentoo.org/~juippis/mozilla/patchsets/firefox-133-patches- …
```
=> www-client/firefox updated to Firefox version 133.0

core-kit/curated/sys-block/thin-provisioning-tools/templates/thin-provisioning-tools.tmpl
Fix compilation when `io-uring` use flag is enabled.
We need to disable unused_qualifications option from rio library.
Closes: macaroni-os/mark-issues#227
=> [core-kit] sys-block/thin-provisioning-tools review template

net-kit/mark/net-fs/minio-client/autogen.yaml, net-kit/mark/net-fs/minio/autogen.yaml
Summary
========
* This update enhances the autogen.yaml files by incorporating the Golang extension to both the Minio and Minio-Client packages. The inclusion aims to streamline development and integration processes related to these packages.
* Closes: macaroni-os/mark-issues#232
Test Plan
========
* Doit
```
╰ $ doit
INFO     Autogen: net-fs/minio (latest)                                                                                                                                                                                      
INFO     Download from https://github.com/minio/minio/tarball/bae05edea0dee78128e59013583b80a8d971c74e verified as valid tar.gz archive.                                                                                     
INFO     Created: …
```
=> net-fs/minio net-fs/minio-client Added Golang extension to Minio and Minio-Client packages

dev-kit/mark/app-emulation/lxd-compose/templates/lxd-compose.tmpl, dev-kit/mark/dev-util/ssh-compose/autogen.yaml, dev-kit/mark/dev-util/ssh-compose/templates/ssh-compose.tmpl
`doit`:
```
$ doit --release mark
INFO     Autogen: dev-util/ssh-compose (latest)                                                                                                                                                      
INFO     Created: ssh-compose-0.6.1.ebuild                                    
```
Test `emerge`:
```
>>> Installing (1 of 1) dev-util/ssh-compose-0.6.1::dev-kit
```
=> [dev-kit] Ssh-compose autogen and minor fix for lxd-compose
